site_name: Ripped
site_url: https://rippedpiracy.github.io 
repo_url: "https://github.com/rippedpiracy/rippedpiracy.github.io"
plugins: []
theme:
    name: null
    custom_dir: 'custom_theme/'
    highlightjs: true
