site_name: Ripped
site_url: https://ripped.guide

repo_url: "https://github.com/rippedpiracy/docs"
repo_name: "GitHub"
edit_uri: "blob/master/"


markdown_extensions:
  - attr_list
  - codehilite
plugins:
  - ezlinks
  - git-revision-date-localized:
      type: date
  - github-contributors:
        repository: 'rippedpiracy/docs'
        contributorsFile: "./docs/contributors.txt"
        excludedIds:
          - 19270622
          - 41898282
          - 90579530
theme:
    name: null
    custom_dir: 'custom_theme/'
    static_templates:
            - 404.html

extra:
    discord_url: "https://discord.gg/6qVr2aR"
